# Site wide configuration

title: tortoise and badger
description: Candy Chang's personal website and portfolio
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: http://127.0.0.1:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Candy Chang
  email: candyichang@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio: slow and steady wins the race.
  avatar: profile_pic.jpg # 160x160 px image for author byline
  # disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
